[workspace]
members = [
    "codegen",
    "canrun",
    "core",
    "goals",
    "examples",
]

# This doesn't work on windows. Not sure if we still need it in macOS or can make it conditional.
# [profile.dev]
# split-debuginfo = "unpacked"
