[workspace]
members = [
    "codegen",
    "canrun",
    "canrun2",
    "examples",
    "extra/mkmvmap"
]

# This doesn't work on windows. Not sure if we still need it in macOS or can make it conditional.
# [profile.dev]
# split-debuginfo = "unpacked"
