name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  stable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run fmt
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install nightly toolchain
        run: rustup toolchain install nightly
      - name: Build
        run: cargo +nightly build --verbose
      - name: Run tests
        run: cargo +nightly test --verbose
