name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  stable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  minimum:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install minimum supported version
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.56.1
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  nightly:
    runs-on: ubuntu-latest

    env:
      CARGO_TARGET_DIR: "./target/coverage"

    steps:
      - uses: actions/checkout@v2
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: llvm-tools-preview

      - name: Install grcov
        run: cargo install grcov

      - name: Build and test
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Zinstrument-coverage -Clink-dead-code"
          RUSTDOCFLAGS: "-Zinstrument-coverage -Clink-dead-code"
          LLVM_PROFILE_FILE: "%p-%m.profraw"
        run: |
          cargo build --verbose
          cargo test --verbose

      - name: Collect coverage
        run: |
          grcov . -s . \
            -t cobertura \
            --binary-path "$CARGO_TARGET_DIR/debug" \
            --llvm --branch --ignore-not-existing \
            -o ./coverage.xml \
            --excl-line '// *coverage-ignore'

      - name: Send to codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update stable
        run: rustup update
      - name: Run clippy
        run: cargo clippy -- --deny clippy::all

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update stable
        run: rustup update
      - name: Run fmt
        run: cargo fmt --all -- --check
