name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  stable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update stable
        run: rustup update
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  minimum:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install minimum supported version
        run: rustup override set 1.54.0
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  nightly:
    runs-on: ubuntu-latest

    env:
      CARGO_TARGET_DIR: "./target/coverage"
      CARGO_INCREMENTAL: "0"
      RUSTFLAGS: "-Zinstrument-coverage -Clink-dead-code"
      RUSTDOCFLAGS: "-Zinstrument-coverage -Clink-dead-code"
      LLVM_PROFILE_FILE: "%p-%m.profraw"

    steps:
      - uses: actions/checkout@v2
      - name: Install nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup component add llvm-tools-preview
          cargo install grcov
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Collect coverage
        run: |
          grcov . -s . \
            -t cobertura \
            --binary-path "$CARGO_TARGET_DIR/debug" \
            --llvm --branch --ignore-not-existing \
            -o ./coverage.xml
      - name: Send to codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update stable
        run: rustup update
      - name: Run clippy
        run: cargo clippy -- --deny clippy::all

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update stable
        run: rustup update
      - name: Run fmt
        run: cargo fmt --all -- --check
